### ISSUE TITLE
UI shows up but errors in console

### ISSUE THREAD

**Issue by abcd-ca** [meteor-useraccounts/ionic#7] opened 2015-05-25 22:02 UTC
Hello, I have my sign-up state showing in my UI but I get these errors in the Chrome console:

```
Exception from Tracker afterFlush function:
debug.js:41 TypeError: Cannot read property 'email' of undefined
    at AT.atInputRendered (at_input.js:4)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:205)
    at view.js:104
    at Object.Blaze._withCurrentView (view.js:523)
    at view.js:103
    at Object.Tracker._runFlush (tracker.js:468)
    at onGlobalMessage (setimmediate.js:102)
debug.js:41 Exception from Tracker afterFlush function:
debug.js:41 TypeError: Cannot read property 'password' of undefined
    at AT.atInputRendered (at_input.js:4)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:205)
    at view.js:104
    at Object.Blaze._withCurrentView (view.js:523)
    at view.js:103
    at Object.Tracker._runFlush (tracker.js:468)
    at onGlobalMessage (setimmediate.js:102)
debug.js:41 Exception from Tracker afterFlush function:
debug.js:41 TypeError: Cannot read property 'password_again' of undefined
    at AT.atInputRendered (at_input.js:4)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:205)
    at view.js:104
    at Object.Blaze._withCurrentView (view.js:523)
    at view.js:103
    at Object.Tracker._runFlush (tracker.js:468)
    at onGlobalMessage (setimmediate.js:102)
```

I'm new to Meteor but I tried,

meteor add useraccounts:ionic
meteor add useraccounts:core
meteor add accounts-password

I'm not sure if I need to run all of those or if I'm missing some? When I click on the Register button, nothing appears to happen but I do get a new document in my db. Nothing happens when I click, 'sign-in'. I could really use an ionic specific step by step.

**Comment by splendido** [comment] 2015-05-30 16:13
Hello @abcd-ca!
do you have a public reproduction for the problem?

**Comment by rootedsoftware** [comment] 2015-06-02 19:49
I'm getting something similar. I reset meteor and still get the same errors. 

I can't login, reset passwords or complete enrollment...

This was me trying to login. 

I20150602-14:32:10.396(-5)? Exception while invoking method 'login' TypeError: Cannot read property 'type' of undefined
I20150602-14:32:10.396(-5)?     at packages/useraccounts:core/lib/server.js:95:1
I20150602-14:32:10.396(-5)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150602-14:32:10.396(-5)?     at packages/meteor/dynamics_nodejs.js:121:1
I20150602-14:32:10.396(-5)?     at packages/accounts-base/accounts_server.js:62:1
I20150602-14:32:10.397(-5)?     at [object Object]._.extend.each (packages/callback-hook/hook.js:102:1)
I20150602-14:32:10.397(-5)?     at validateLogin (packages/accounts-base/accounts_server.js:59:1)
I20150602-14:32:10.397(-5)?     at attemptLogin (packages/accounts-base/accounts_server.js:251:1)
I20150602-14:32:10.397(-5)?     at [object Object].Meteor.methods.login (packages/accounts-base/accounts_server.js:411:1)
I20150602-14:32:10.397(-5)?     at packages/check/match.js:109:1
I20150602-14:32:10.397(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)

This was from trying to complete the verifyEmail. 

I20150602-14:33:00.446(-5)? Exception while invoking method 'verifyEmail' TypeError: Cannot read property 'type' of undefined
I20150602-14:33:00.446(-5)?     at packages/useraccounts:core/lib/server.js:95:1
I20150602-14:33:00.446(-5)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150602-14:33:00.446(-5)?     at packages/meteor/dynamics_nodejs.js:121:1
I20150602-14:33:00.446(-5)?     at packages/accounts-base/accounts_server.js:62:1
I20150602-14:33:00.446(-5)?     at [object Object]._.extend.each (packages/callback-hook/hook.js:102:1)
I20150602-14:33:00.446(-5)?     at validateLogin (packages/accounts-base/accounts_server.js:59:1)
I20150602-14:33:00.446(-5)?     at attemptLogin (packages/accounts-base/accounts_server.js:251:1)
I20150602-14:33:00.446(-5)?     at Object.Accounts._loginMethod (packages/accounts-base/accounts_server.js:273:1)
I20150602-14:33:00.446(-5)?     at [object Object].Meteor.methods.verifyEmail (packages/accounts-password/password_server.js:634:1)
I20150602-14:33:00.447(-5)?     at packages/check/match.js:109:1

**Comment by rootedsoftware** [comment] 2015-06-02 20:17
When I downgrade from 

useraccounts:core@1.11.0
useraccounts:ionic@1.11.0

To
useraccounts:core@1.9.1
useraccounts:ionic@1.9.1

The problem goes away

**Comment by splendido** [comment] 2015-06-03 18:51
Hello Josh,
your problem was caused by https://github.com/meteor-useraccounts/core/issues/413, which is now fixed!

**Comment by splendido** [comment] 2015-06-03 18:54
Lets continue the discussion [here](https://github.com/meteor-useraccounts/core/issues/367) (which seems the same issue).

**Closed as completed by splendido** 2015-06-03 18:54 UTC
